name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout ffmpeg
        uses: actions/checkout@v3   
        with:
          repository: FFmpeg/FFmpeg
          path: Ffmpeg
      - name: Install Ffmpeg aptitude deps
        run: sudo apt-get install -y yasm libx264-dev
      - name: Build ffmpeg
        run: cd  Ffmpeg && ./configure --enable-gpl --enable-shared --shlibdir=/lib/x86_64-linux-gnu/ --enable-libx264 && make && sudo make install && sudo ldconfig
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run ldconfig
        run: ldconfig -p
      - run: npm ci
      - run: npm test